apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: fluidd
  name: fluidd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fluidd
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/klipper-default: "true"
        io.kompose.service: fluidd
    spec:
      containers:
        - image: dimalo/fluidd
          name: fluidd
          ports:
            - containerPort: 80
              hostPort: 8010
              protocol: TCP
      restartPolicy: Always
