apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: klipper
  name: klipper
spec:
  ports:
    - name: "7125"
      port: 7125
      targetPort: 7125
  selector:
    io.kompose.service: klipper
